### ISSUE TITLE
Unable to open GameData files

### ISSUE THREAD

**Issue by danieljianu** [gamedevware/charon-unity3d#3]
If there is a <space> character somewhere in the name of one of the project folders where the GameData document resides, it fails to open it with the error:
`Error: Could not find a part of the path "/Project%20Path/Data/GameData.gdjs"`.

Probably because it's replacing the <space> with <%20> and it no longer resolves to the actual path.

**Comment by deniszykov** [comment]
Hi @danieljianu! Thanks for report, I will investigate it.

**Comment by deniszykov** [comment]
fixed in version 2018.4.4. 
You could update in **Unity Editor - Tools - Charon - Check for updates** ...

**Comment by danieljianu** [comment]
Thank you for the quick reaction!

I updated to 2018.4.4 but now I'm seeing this error:

`Error: Could not find a part of the path "/Users/<user>/Documents/<project path>/Users/<user>/Documents/<project path>/Assets/GameData.gdjs".`

As you can see, now it's somehow doubling the root path it's trying to find the file on.

FYI, I'm running this on a Mac OS 10.14.

Thanks again!

**Comment by deniszykov** [comment]
> FYI, I'm running this on a Mac OS 10.14.

It's time to dust off my Mac mini :)

**Comment by danieljianu** [comment]
:) Please let me know if you need more debug information on my end.

**Comment by deniszykov** [comment]
Hi @danieljianu. Updated to 2018.4.5 and checked on MacOS. Also worth mentioning it doesn't work with Mono 5.10 on MacOS. Last version of Mono is fine.

**Comment by danieljianu** [comment]
It's finally working!
Thank you very much, amazing support.

I'll make sure to add a review on the Asset Store. :)

**Comment by deniszykov** [comment]
Welcome! And thanks in advance for review!
