### ISSUE TITLE
Unsigned Byte

### ISSUE THREAD

**Issue by JamesMac64** [gamedevware/charon-unity3d#9]
Is there a way to specify an unsigned byte?  (I am fairly sure that you can, but I haven't found any documentation on doing so.)
I use a lot of byte and short values, with the bytes being unsigned so that I can always use the smallest data type possible to keep things efficient on memory and network usage.  But every time I set an integer at one byte, the code generated is for an sbyte.

**Comment by deniszykov** [comment]
Hi @JamesMac64! 
Currently there is no way to specify unsigned integers. For smallest network footprint use [Message Pack](https://msgpack.org/index.html) game data format and gzip compression. This format has build-in small integer encoding. As for runtime memory footprint I think 2 bytes instead of 1 is not big deal considering .NET could layout class field as he like. For [example](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.structlayoutattribute.pack?view=net-5.0) with 4 bytes alignment is used by default.

**Comment by JamesMac64** [comment]
Thanks for the response. I considered using a short (2 bytes) and it doesn't seem like much of an overhead using 2 bytes vice 1, but in an MMO game design it does add up on the server.  Besides, the guys that I am working with are still more of an intern level developer and I want them to learn things the right way first, then learn to adapt when required.  I retired back in 2006 and I do this as a volunteer to help these guys, and to have something productive to do.  I'm not dead yet.  It is an experience for me though, as this project is Unity based and c#, vice c++ and either build our own engine or mostly I worked with UE2 until I retired.  Unity has been a learning experience, just having the Unity editor is a huge change for me.  When I joined the project, everything was a 4 byte int, a float, or mostly strings, the worst thing to use in an MMO at 4 bytes per character and using them as an index or key value.  Just in an accountID a string used 68 bytes vice 8 bytes as a ulong.
The asset is quite nice by the way, and testing it the overhead isn't bad at all, and it does a great job.  I still have to spend time changing the localization system over, which I am changing from using a string key value to a short and using your asset for xml storage vice the bunch of flat text files, but I am not quite ready to rebuild that system yet.  Too much else to do.  I've gutted the entire core and rebuilt it from the ground up.
For the Localized message system, I am only going to be sending the short key value over the network instead of the strings.  That will reduce the load it places on the network system the most effectively.  For chat, I am open to suggestions.
The current project goal is 1000 concurrent players, and until I rebuilt it the server side could not handle more than about 60 before it was peaking out server memory usage.  The servers are commercial rigs in a datacenter with a high end connection to the backbone, so we haven't pushed that limit yet.
For now I will stick with editing the generated class to use bytes instead of sbytes.  The kid who designed the game is still figuring things out, so needless to say I keep having to go back and make changes to things like the item and stat effect systems, and thus I have to also go back and edit the generated class.  I've sped that up by using a find/replace on the sbytes with case sensitive, and then manually fix the 6 errors that creates for what should have remained sbytes.

**Comment by deniszykov** [comment]
If you need deep customization of generated code, you could [export](https://github.com/deniszykov/charon-unity3d/wiki/Exporting%20Code%20Generation%20Templates) [T4 Templates](https://docs.microsoft.com/en-us/visualstudio/modeling/code-generation-and-t4-text-templates?view=vs-2019), edit and run them with VS or Rider or Xamarin Studio (Unity Code Editor). This is better way, but complex. Also good luck with your journey into optimization of MMO and thanks for your feedback!
